.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SUBTLER" "1" "October 2011" "" ""
.
.SH "NAME"
\fBsubtler\fR \- a commandline interface for subtle
.
.SH "SYNOPSIS"
\fBsubtler\fR [GENERIC|MODIFIER] [GROUP] [ACTION]
.
.SH "DESCRIPTION"
\fBsubtler\fR is a commandline tool, that allows interacting with a \fBEWMH/NetWM\fR compatible window manager and especially with subtle(1) from a shell\.
.
.SH "FORMATS"
.
.IP "\(bu" 4
\fBDISPLAY\fR :\fIdisplay number\fR
.
.IP "\(bu" 4
\fBID\fR \fInumber\fR
.
.IP "\(bu" 4
\fBGEOMETRY\fR <xx\fIy\fR+\fIwidth\fR+\fIheight\fR
.
.IP "\(bu" 4
\fBPATTERN\fR
.
.br
Matching works either via plaintext, regex(7), id or window id if applicable\. If a pattern matches more than once ALL matches are used\.
.
.IP
If the \fBPATTERN\fR is \- subtler will read from stdin\.
.
.IP "" 0
.
.SH "OPTIONS"
.
.SH "GENERIC"
.
.IP "\(bu" 4
\fB\-d\fR, \fB\-\-display\fR=DISPLAY
.
.br
Connect to DISPLAY (default: :0)
.
.IP "\(bu" 4
\fB\-h\fR, \fB\-\-help\fR
.
.br
Show this help and exit
.
.IP "\(bu" 4
\fB\-V\fR, \fB\-\-version\fR
.
.br
Show version info and exit
.
.IP "\(bu" 4
\fB\-p\fR, \fB\-\-proc\fR
.
.br
This creates a ruby proc from the given argument and yields the result of the group to it as parameter \fIparam\fR\.
.
.IP
Examples:
.
.IP
subtler \-cl \-p "puts param\.name" subtler \-cC \-p "param\.gravity = { terms: :left }"
.
.IP "" 0
.
.SH "MODIFIER"
.
.IP "\(bu" 4
\fB\-r\fR, \fB\-\-reload\fR
.
.br
Reload subtle
.
.IP "\(bu" 4
\fB\-R\fR, \fB\-\-restart\fR
.
.br
Restart subtle
.
.IP "\(bu" 4
\fB\-Q\fR, \fB\-\-quit\fR
.
.br
Quit subtle
.
.IP "\(bu" 4
\fB\-C\fR, \fB\-\-current\fR
.
.br
Select current active window/view
.
.IP "\(bu" 4
\fB\-X\fR, \fB\-\-select\fR
.
.br
Select a window via pointer
.
.IP "" 0
.
.SH "GROUPS"
.
.IP "\(bu" 4
\fB\-c\fR, \fB\-\-client\fR
.
.br
Use client group
.
.IP "\(bu" 4
\fB\-g\fR, \fB\-\-gravity\fR
.
.br
Use gravity group
.
.IP "\(bu" 4
\fB\-e\fR, \fB\-\-screen\fR
.
.br
Use screen group
.
.IP "\(bu" 4
\fB\-s\fR, \fB\-\-sublet\fR
.
.br
Use sublet group
.
.IP "\(bu" 4
\fB\-t\fR, \fB\-\-tag\fR
.
.br
Use tag group
.
.IP "\(bu" 4
\fB\-y\fR, \fB\-\-tray\fR
.
.br
Use tray group
.
.IP "\(bu" 4
\fB\-v\fR, \fB\-\-view\fR
.
.br
Use views group
.
.IP "" 0
.
.SH "ACTIONS FOR CLIENTS"
.
.IP "\(bu" 4
\fB\-f\fR, \fB\-\-find\fR=PATTERN
.
.br
Find client
.
.IP "\(bu" 4
\fB\-o\fR, \fB\-\-focus\fR=PATTERN
.
.br
Set focus to client
.
.IP "\(bu" 4
\fB\-F\fR, \fB\-\-full\fR
.
.br
Toggle full
.
.IP "\(bu" 4
\fB\-O\fR, \fB\-\-float\fR
.
.br
Toggle float
.
.IP "\(bu" 4
\fB\-S\fR, \fB\-\-stick\fR
.
.br
Toggle stick
.
.IP "\(bu" 4
\fB\-N\fR, \fB\-\-urgent\fR
.
.br
Toggle urgent
.
.IP "\(bu" 4
\fB\-l\fR, \fB\-\-list\fR
.
.br
List all clients
.
.IP "\(bu" 4
\fB\-T\fR, \fB\-\-tag\fR=PATTERN
.
.br
Add tag to client
.
.IP "\(bu" 4
\fB\-U\fR, \fB\-\-untag\fR=PATTERN
.
.br
Remove tag from client
.
.IP "\(bu" 4
\fB\-G\fR, \fB\-\-tags\fR
.
.br
Show client tags
.
.IP "\(bu" 4
\fB\-Y\fR, \fB\-\-gravity\fR
.
.br
Set client gravity
.
.IP "\(bu" 4
\fB\-E\fR, \fB\-\-raise\fR
.
.br
Raise client window
.
.IP "\(bu" 4
\fB\-L\fR, \fB\-\-lower\fR
.
.br
Lower client window
.
.IP "\(bu" 4
\fB\-k\fR, \fB\-\-kill\fR=PATTERN
.
.br
Kill client
.
.IP "" 0
.
.SH "ACTIONS FOR GRAVITIES"
.
.IP "\(bu" 4
\fB\-a\fR, \fB\-\-add\fR=NAME
.
.br
Create new gravity
.
.IP "\(bu" 4
\fB\-l\fR, \fB\-\-list\fR
.
.br
List all gravities
.
.IP "\(bu" 4
\fB\-f\fR, \fB\-\-find\fR=PATTERN
.
.br
Find a gravity
.
.IP "\(bu" 4
\fB\-k\fR, \fB\-\-kill\fR=PATTERN
.
.br
Kill gravity
.
.IP "" 0
.
.SH "ACTIONS FOR SCREENS"
.
.IP "\(bu" 4
\fB\-l\fR, \fB\-\-list\fR
.
.br
List all screens
.
.IP "\(bu" 4
\fB\-f\fR, \fB\-\-find\fR=ID
.
.br
Find a screen
.
.IP "" 0
.
.SH "ACTIONS FOR SUBLETS"
.
.IP "\(bu" 4
\fB\-a\fR, \fB\-\-add\fR=FILE
.
.br
Create new sublet
.
.IP "\(bu" 4
\fB\-l\fR, \fB\-\-list\fR
.
.br
List all sublets
.
.IP "\(bu" 4
\fB\-u\fR, \fB\-\-update\fR
.
.br
Updates value of sublet
.
.IP "\(bu" 4
\fB\-A\fR, \fB\-\-data\fR
.
.br
Set data of sublet
.
.IP "\(bu" 4
\fB\-k\fR, \fB\-\-kill\fR=PATTERN
.
.br
Kill sublet
.
.IP "" 0
.
.SH "ACTIONS FOR TAGS"
.
.IP "\(bu" 4
\fB\-a\fR, \fB\-\-add\fR=NAME
.
.br
Create new tag
.
.IP "\(bu" 4
\fB\-f\fR, \fB\-\-find\fR
.
.br
Find all clients/views by tag
.
.IP "\(bu" 4
\fB\-l\fR, \fB\-\-list\fR
.
.br
List all tags
.
.IP "\(bu" 4
\fB\-I\fR, \fB\-\-clients\fR
.
.br
Show clients with tag
.
.IP "\(bu" 4
\fB\-k\fR, \fB\-\-kill\fR=PATTERN
.
.br
Kill tag
.
.IP "" 0
.
.SH "ACTIONS FOR TRAYS"
.
.IP "\(bu" 4
\fB\-f\fR, \fB\-\-find\fR=PATTERN
.
.br
Find a tray
.
.IP "\(bu" 4
\fB\-l\fR, \fB\-\-list\fR List all trays
.
.IP "\(bu" 4
\fB\-k\fR, \fB\-\-kill\fR=TRAY
.
.br
Kill tray
.
.IP "" 0
.
.SH "ACTIONS FOR VIEWS"
.
.IP "\(bu" 4
\fB\-a\fR, \fB\-\-add\fR=NAME
.
.br
Create new view
.
.IP "\(bu" 4
\fB\-f\fR, \fB\-\-find\fR=PATTERN
.
.br
Find a view
.
.IP "\(bu" 4
\fB\-l\fR, \fB\-\-list\fR List all views
.
.IP "\(bu" 4
\fB\-T\fR, \fB\-\-tag\fR=PATTERN
.
.br
Add tag to view
.
.IP "\(bu" 4
\fB\-U\fR, \fB\-\-untag\fR=PATTERN
.
.br
Remove tag from view
.
.IP "\(bu" 4
\fB\-G\fR, \fB\-\-tags\fR Show view tags
.
.IP "\(bu" 4
\fB\-I\fR, \fB\-\-clients\fR Show clients on view
.
.IP "\(bu" 4
\fB\-k\fR, \fB\-\-kill\fR=VIEW
.
.br
Kill view
.
.IP "" 0
.
.SH "LISTINGS"
Client listing: \fIwindow id\fR [\-\fI] \fIview id\fR \fIgeometry\fR \fIgravity\fR \fIflags\fR \fIinstance name\fR (\fIclass name\fR)
.
.br
Gravity listing: \fIgravity id\fR \fIgeometry\fR
.
.br
Screen listing: \fIscreen id\fR \fIgeometry\fR
.
.br
Tag listing: \fItag name\fR
.
.br
Tray listing: \fIwindow id\fR \fIinstance name\fR (\fIclass name\fR) View listing: \fIwindow id\fR [\-\fR] \fIview id\fR \fIview name\fR
.
.SH "EXAMPLES"
subtler \-c \-l List all clients
.
.br
subtler \-t \-a subtle Add new tag \'subtle\'
.
.br
subtler \-v subtle \-T rocks Tag view \'subtle\' with tag \'rocks\'
.
.br
subtler \-c xterm \-G Show tags of client \'xterm\'
.
.br
subtler \-c \-X \-f Select client and show info
.
.br
subtler \-c \-C \-Y 5 Set gravity 5 to current active client
.
.br
subtler \-t \-f term Show every client/view tagged with \'term\'
.
.SH "BUGS"
Report bugs at http://subforge\.org/projects/subtle/issues
.
.br
Homepage: http://subtle\.subforge\.org
.
.SH "COPYRIGHT"
Copyright (c) Christoph Kappel \fIunexist@subforge\.org\fR
.
.SH "SEE ALSO"
subtle(1), subtlext(1), sur(1), surserver(1)
